apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}{{ .Values.nameSuffix }}
  namespace: showks
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: app-port
  selector:
    app: {{ .Chart.Name }}
